// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistradorDeProcessos.WebAPI.Contextos;

namespace RegistradorDeProcessos.WebAPI.Migrations
{
    [DbContext(typeof(RegistradorDeProcessosContexto))]
    [Migration("20200307193554_CatalogoInicial")]
    partial class CatalogoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("RegistradorDeProcessos.WebAPI.Model.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Legenda")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiAnexo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessoNumero")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoNumero");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("RegistradorDeProcessos.WebAPI.Model.Processo", b =>
                {
                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assunto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Distribuicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relator")
                        .HasColumnType("TEXT");

                    b.HasKey("Numero");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("RegistradorDeProcessos.WebAPI.Model.Movimentacao", b =>
                {
                    b.HasOne("RegistradorDeProcessos.WebAPI.Model.Processo", null)
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProcessoNumero");
                });
#pragma warning restore 612, 618
        }
    }
}
